// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPphgpD5b9HGkr4ZzhrTkp5M1wgb63ST0',
    appId: '1:134602236903:web:d3e1cff60acf350a5fd342',
    messagingSenderId: '134602236903',
    projectId: 'sba7ota7adii',
    authDomain: 'sba7ota7adii.firebaseapp.com',
    storageBucket: 'sba7ota7adii.appspot.com',
    measurementId: 'G-2RK3QJFBC6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALcHaPSLgbMREdHMcR8tc_QfbfcUh87Hs',
    appId: '1:134602236903:android:2361932f1be29d865fd342',
    messagingSenderId: '134602236903',
    projectId: 'sba7ota7adii',
    storageBucket: 'sba7ota7adii.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKRDRi0oYwCuwZl7jElHfZdWIu4z5OhEE',
    appId: '1:134602236903:ios:c83ec750c88cd0805fd342',
    messagingSenderId: '134602236903',
    projectId: 'sba7ota7adii',
    storageBucket: 'sba7ota7adii.appspot.com',
    iosBundleId: 'com.example.spa7oTa7adii',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKRDRi0oYwCuwZl7jElHfZdWIu4z5OhEE',
    appId: '1:134602236903:ios:7441712876d2b1da5fd342',
    messagingSenderId: '134602236903',
    projectId: 'sba7ota7adii',
    storageBucket: 'sba7ota7adii.appspot.com',
    iosBundleId: 'com.example.spa7oTa7adii.RunnerTests',
  );
}
